config/routes.rb
Rails.application.routes.draw do
  resources :cars

  root 'locations#index'

  resources :users

  get 'cars/nearby/available' => 'cars#nearby_and_available'
  resources :cars, only: [:create] do
    member do
      put :book
    end
    collection do
      post '/:device_id/update_location', to: 'cars#update_location'
    end
  end

  resources :car_bookings do
    collection do
      get '/user', to: 'car_bookings#fetch_drives'
      put '/:device_id/start_trip', to: 'car_bookings#start_trip'
      post '/:device_id/close_trip', to: 'car_bookings#close_trip'
    end
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude

  def self.nearby_and_available(latitude, longitude)
    Car.where(available: true).near([latitude, longitude], 20)
  end
end

app/models/car_booking.rb
class CarBooking < ActiveRecord::Base
  module Status
    SCHEDULED="scheduled"
    CANCELLED="cancelled"
    CLOSED="closed"
  end

  module Types
    BOOK_NOW = "Book now"
    BOOK_LATER = "Book for later"
  end

  belongs_to :car
  belongs_to :user

  def compute_amount
    distance * 12;
  end
end

app/models/license.rb
class License < ActiveRecord::Base
end

app/models/licenses_user.rb
class LicensesUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :license
end

app/models/user.rb
class User < ActiveRecord::Base
  def save_license(license)
    license = License.new(filename: license.original_filename, content_type: license.content_type, file_contents: license.tempfile.read)
    license.save
    LicensesUser.create(user: self, license: license)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/car_bookings_controller.rb
class CarBookingsController < ApplicationController
  before_action :load_models, except: [:fetch_drives]

  def start_trip
    @current_booking.update_attributes(start_time: DateTime.now, start_latitude: params[:latitude], start_longitude: params[:longitude])
    render json: @current_booking
  end

  def close_trip
    amount = @current_booking.compute_amount
    @current_booking.update_attributes(:end_time => Time.now, :end_latitude => @car.latitude, :end_longitude => @car.longitude,
                                       :status => CarBooking::Status::CLOSED, :amount => amount)
    @car.update_attributes(:available => true)
    render json: @current_booking
  end

  def fetch_drives
    user = User.where(email: params[:email]).first
    car_bookings = CarBooking.where(user: user)
    render json: car_bookings
  end

  private
  def load_models
    @car = Car.find_by_device_id(params[:device_id])
    @current_booking = CarBooking.find_by_car_id_and_status(@car.id, CarBooking::Status::SCHEDULED)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show]

  def index
    render json: Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_location
    car = Car.find_by_device_id(params[:device_id])
    new_latitude = params[:latitude]
    new_longitude = params[:longitude]
    car.update_attributes(:latitude => new_latitude, :longitude => new_longitude)
    current_booking = CarBooking.find_by_car_id_and_status(car.id, CarBooking::Status::SCHEDULED)
    if current_booking
      updated_distance = current_booking.distance + car.distance_to([new_latitude, new_longitude])
      current_booking.update_attributes(:distance => updated_distance)
    end
    render json: {latitude: car.latitude, longitude: car.longitude}
  end

  def book
    user = User.where(email: params[:email]).first
    car = Car.find_by(id: params[:id])
    booking_type = params[:booking_type]
    booking_time = nil
    unless params[:booking_type] == CarBooking::Types::BOOK_NOW
      today = Date.today
      booking_time = DateTime.new(today.year, today.month, today.day, params[:booking_hour].to_i, params[:booking_minute].to_i, 0)
    end
    car_booking = CarBooking.new(car: car, user: user, status: CarBooking::Status::SCHEDULED, booking_time: booking_time, booking_type: booking_type)
    car.update_attributes(available: false) if car_booking.save
    render json: car_booking
  end

  def nearby_and_available
    cars = Car.nearby_and_available(params[:latitude].to_d, params[:longitude].to_d)
    render json: cars
  end

  private
  def set_car
    @car = Car.find(params[:id])
  end
  def car_params
    params.require(:car).permit(:name, :number, :make, :device_id, :latitude, :longitude)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter  :verify_authenticity_token, only: [:create]

  def create
    user_params = {full_name: params[:full_name], age: params[:age].to_i, sex: params[:sex], email: params[:email], password: params[:password]}
    license = params[:license]
    user = User.new(user_params)
    user.save
    user.save_license(license)
    render json: {status: :ok}
  end

  def index
    render json: User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :device_id %><br>
    <%= f.text_field :device_id %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Make</th>
      <th>Device</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= car.number %></td>
        <td><%= car.make %></td>
        <td><%= car.device_id %></td>
        <td><%= car.latitude %></td>
        <td><%= car.longitude %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @car.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @car.number %>
</p>

<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Device:</strong>
  <%= @car.device_id %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @car.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @car.longitude %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UdriveServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/index.html.haml
= 'Fetching locations...'